name: Merge to Main

on:
  push:
    branches:
      - test

jobs:
  merge_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Merge to Main
        run: |
          git fetch origin test
          changes=$(git rev-list HEAD...origin/test --count)
          echo "Number of changes: $changes"
          if [ "$changes" -gt 0 ]; then
            # Changes exist, proceed with the merge
            git checkout test
            git merge --no-ff main
            git push origin test:main
          else
            # No changes, no need to merge
            echo "No changes to merge."
          fi
